// Copyright (c) 2023-2026 Brendan Bycroft. MIT License.
// Develo engine public exports.
//
// runtime/engine.js is a committed build artifact: the site ships plain ES
// modules with no production build step, so the bundle is regenerated by hand
// whenever anything under upstream/ or theme.ts changes.
//
// Typecheck: npx -p typescript tsc -p features/llm-visualization/tsconfig.json
// Bundle:    npx esbuild features/llm-visualization/engine-entry.ts --bundle \
//              --format=esm --target=es2020 \
//              --alias:@=./features/llm-visualization/upstream \
//              --outfile=features/llm-visualization/runtime/engine.js

export { LLM_VIZ_ASSET_BASE, fetchRequiredAsset, fetchJsonAsset, instantiateLlmWasm } from "./upstream/src/utils/assetBase";
export { initProgramState, runProgram, NANO_SHAPE } from "./upstream/src/llm/Program";
export type { IProgramState, DeveloVizStage } from "./upstream/src/llm/Program";
export { startDeveloWalkthrough, pauseDeveloWalkthrough, resetDeveloWalkthrough, getDeveloWalkthroughSnapshot, setDeveloWalkthroughSpeed } from "./upstream/src/llm/walkthrough-develo/DeveloWalkthrough";
export { initRender } from "./upstream/src/llm/render/modelRender";
export { fetchFontAtlasData } from "./upstream/src/llm/render/fontRender";
export { loadNativeBindings } from "./upstream/src/llm/NativeBindings";
export { constructModel, createGpuModelForWasm, stepWasmModel, syncWasmDataWithJsAndGpu, resetWasmModelInput } from "./upstream/src/llm/GptModelWasm";
export { initModel, setModelInputData } from "./upstream/src/llm/GptModel";
export { TensorF32 } from "./upstream/src/utils/tensor";
export { Vec3, Vec4 } from "./upstream/src/utils/vector";
export { cameraToMatrixView, updateCamera } from "./upstream/src/llm/Camera";
